name: "Test CLI functionality"
on:
  workflow_run:
    workflows:
      - "Run all tests"
    branches:
      - "mistress"
    types:
      - "completed"

jobs:
  run-tests:
    strategy:
      matrix:
        version: ["stable", "nightly", "1.64"]
    if: "github.actor != 'dependabot'"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
          components: "clippy"
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "clippy"
      - name: "Make sure the CLI passes valid config"
        run: "cargo run -p there-cli -- plan validate -f ./test/plan.yaml"
      - name: "Make sure the CLI fails invalid config"
        run: "cargo run -p there-cli -- plan validate -f ./test/invalid-plan.yaml"
